{% set name = "rexml" %}
{% set version = "3.2.9" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: a58fe5a92987d1f82ad29fc3822bd2dab73ece2fabca37f3b2b2a9d82358fd1e

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}
    - rb-strscan >=0

test:
  commands:
    - ruby -r rexml -e 'exit 0'

about:
  home: https://rubygems.org/gems/rexml
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A XML toolkit for Ruby

  doc_url: https://www.rubydoc.info/gems/rexml
  dev_url: https://github.com/ruby/rexml

extra:
  recipe-maintainers:
    - ajaypnair09
    - jdmarques
    - rudispr
